Multiple Linear Regression is one of the important regression algorithms which models the linear relationship between a single dependent continous variable and more than one independent variable.

# Importing the Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Importing Dataset

In [2]:
df=pd.read_csv("50_Startups.csv")

In [3]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [6]:
df.describe().T

count         mean            std       min          25%  \
R&D Spend         50.0   73721.6156   45902.256482      0.00   39936.3700   
Administration    50.0  121344.6396   28017.802755  51283.14  103730.8750   
Marketing Spend   50.0  211025.0978  122290.310726      0.00  129300.1325   
Profit            50.0  112012.6392   40306.180338  14681.40   90138.9025   

                        50%          75%        max  
R&D Spend         73051.080  101602.8000  165349.20  
Administration   122699.795  144842.1800  182645.56  
Marketing Spend  212716.240  299469.0850  471784.10  
Profit           107978.190  139765.9775  192261.83

In [7]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

# Encoding Categorical Data

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [14]:
x

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [16]:
cde=pd.get_dummies(df)
cde.head(5)

R&D Spend  Administration  Marketing Spend     Profit  State_California  \
0  165349.20       136897.80        471784.10  192261.83                 0   
1  162597.70       151377.59        443898.53  191792.06                 1   
2  153441.51       101145.55        407934.54  191050.39                 0   
3  144372.41       118671.85        383199.62  182901.99                 0   
4  142107.34        91391.77        366168.42  166187.94                 0   

   State_Florida  State_New York  
0              0               1  
1              0               0  
2              1               0  
3              0               1  
4              1               0

# Splitting the dataset into training dataset and test dataset

In [18]:
from sklearn.model_selection import train_test_split
x_tr,xt,y_tr,yt=train_test_split(x,y,test_size=0.2,random_state=1)

# Training the multi linear regression model on the training dataset

In [19]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_tr,y_tr)

LinearRegression()

# Predicting with Test Dataset

In [20]:
y_predict=regressor.predict(xt)
y_predict

array([114664.41715867,  90593.15531621,  75692.84151575,  70221.88679652,
       179790.25514872, 171576.9201852 ,  49753.5875203 , 102276.65888936,
        58649.37795761,  98272.02561131])

In [22]:
x1=regressor.predict([[0,0,1,160000,170000,150000]])

In [26]:
print(x1)

[176449.55364226]


# Checking the coefficient and intercept

In [24]:
regressor.intercept_

49834.885073226884

In [25]:
regressor.coef_

array([-2.85177769e+02,  2.97560876e+02, -1.23831070e+01,  7.74342081e-01,
       -9.44369585e-03,  2.89183133e-02])